name: 'ci'
on: push

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # Cache dependencies
      - run: pip install -r requirements.txt
      - run: pip install pytest coverage
      - name: "Run tests with coverage"
        run: coverage run -m pytest
      - run: ls -la ; echo $PWD
      - name: "Upload coverage"
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: .coverage
          retention-days: 1

  coverage_report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # Cache dependencies
      - run: pip install coverage
      - name: "Get coverage data"
        uses: actions/download-artifact@v2
        with:
          name: test-coverage
      - name: "Create coverage report"
        run: coverage report
      - name: "Create coverage report (XML)"
        run: coverage xml -o coverage.xml
      - name: "Upload coverage report (XML)"
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          retention-days: 14

